# -*- coding: utf-8 -*-
"""nuvem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTSji4_X61O1yzoPYXC7HH_GYozSHETA
"""



import streamlit as st
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Sample text related to the Marvel Universe
marvel_text = """
Spider-Man Iron_Man Captain_America Thor Hulk Black_Widow Wolverine Cyclops Jean_Grey Storm Magneto Professor_X Doctor_Strange Scarlet_Witch Vision Falcon Winter_Soldier Black_Panther Ant-Man Wasp Deadpool Thanos Loki Venom Carnage Ultron Green_Goblin
Asgard Wakanda X-Mansion Sanctum_Sanctorum New_York_City Latveria Savage_Land Negative_Zone K'un-Lun
Flight Super_Strength Telekinesis Telepathy Energy_Blasts Regeneration Web-Slinging Shapeshifting Size_Alteration Magic Invulnerability Mutation Teleportation Mind_Control Super_Speed
Infinity_Stones Multiverse Avengers X-Men Fantastic_Four Guardians_of_the_Galaxy SHIELD HYDRA Vibranium Adamantium Pym_Particles Cosmic_Cube Mjolnir Shield Arc_Reactor Sentinels Kree Skrulls Celestials Inhumans Mutants Homo_Superior
Doctor_Doom Galactus Mystique Deadpool Punisher Daredevil Elektra Ghost_Rider Blade Silver_Surfer Nick_Fury Captain_Marvel Hawkeye Vision War_Machine Star-Lord Gamora Drax Rocket Groot Dormammu Red_Skull Baron_Zemo
"""

st.set_page_config(layout="wide")
st.title("Nuvem de Palavras do Universo Marvel")

st.write("Esta aplicação gera uma nuvem de palavras baseada em termos do vasto universo da Marvel, incluindo personagens, locais, poderes e conceitos.")

@st.cache_data
def generate_wordcloud(text):
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
    return wordcloud

# Generate the word cloud
wordcloud = generate_wordcloud(marvel_text)

# Display the word cloud using matplotlib
fig, ax = plt.subplots(figsize=(10, 5))
ax.imshow(wordcloud, interpolation='bilinear')
ax.axis("off")
st.pyplot(fig)

st.markdown("--- ")
st.markdown("**Como executar:** Salve este código como `app.py` e execute no seu terminal com `streamlit run app.py`.")